### PR TITLE
admin forms descriptions inline with "Toggle Inline Help" button

### PR DESCRIPTION
**Pull request by trob**

### CODE REVIEW

**Comment by joomlahenk** [comment]
Don't use class="controls" as this is blocking BS5 classes, that's why I removed them.
"controls" was used in:
administrator\components\com_fabrik\models\plugin.php
administrator\components\com_fabrik\views\form\tmpl\bootstrap_process.php
administrator\components\com_fabrik\views\lists\tmpl\confirmdeletebootstrap.php
components\com_fabrik\models\plugin.php
components\com_fabrik\views\details\tmpl\bootstrap_tabs\default_group_labels_side.php
components\com_fabrik\views\form\tmpl\bootstrap\default_group_labels_side.php
components\com_fabrik\views\form\tmpl\bootstrap_tabs\default_group_labels_side.php
components\com_fabrik\views\import\tmpl\bootstrap.php

Maybe you need to check if all of these now require 'descriptions'.

**Comment by trob** [comment]
Not sure what you mean, I didn't add class="controls" somewhere (green background is the new code)

The "descriptions" are for backend admin forms only not for "user" forms, so components\com_fabrik\views\... aren't touched at all.

**Comment by trob** [comment]
Are you referring to renderfield.php?
This is the original Joomla code.
I just tested without class="controls" but this is breaking the backend admin forms layout.

**Comment by joomlahenk** [comment]
class="controls" in in administrator/components/com_fabrik/layouts/joomla/form/renderfield.php line 55
Maybe "control" is used here as a 'custom' class, not as a BS class and there is no BS5 that may be blocked.
Anyway, I will merge and see what it does. Looks quite simple in this way.

**Pull request merged**
