### PR TITLE
Password element, more j3 in plugins

### PR DESCRIPTION
**Pull request by trob**
Use FabrikWorker::getCrypt() in  formsession.php ('simple' is not longer supported in J!4)
Use UserHelper::hashPassword (getCryptedPassword is not longer supported in J!4)

### CODE REVIEW

**Comment by joomlahenk** [comment]
Yes, you will find j3 in most plugins. I never updated those.

**Comment by joomlahenk** [comment]
Further if you changed $options->j3 = true; then you can also go for the j3's and comment out the not true's, then remove $options->j3 = true; as well. Makes not a big change, but we have lesser code.

**Comment by trob** [comment]
Yes, but thinking of backward compatibility in layout overrides etc. I would leave things like $display->j3.
It's a question of "clean code" against "keep it as simple as possible for updating users".

**Comment by joomlahenk** [comment]
We will not have backward compatibility and all j3 is removed from the core files, so why not also remove from plugins?
I don't see the benifit for updating users, maybe it's even more confusing. Later we may get updates for J!4.x

**Comment by trob** [comment]
I now removed all j3 from plugins, hopefully without introducing typos.

**Pull request merged**
