### PR TITLE
Update linker, build and mootools

### PR DESCRIPTION
**Pull request by skurvish**
Mootools is now installed into the media/com_fabrik/js folder and the files that load it have been changed to find the files there.
Updated the build process to include the latest plugins that have been tested.
Updated the linker.xml file to link all of these plugins along with the media/com_fabrik folder. Link & unlink seem to work well.

### CODE REVIEW

**Comment by skurvish** [comment]
I don't understand what you mean by change elements.

**Comment by joomlahenk** [comment]
You changed:
administrator/components/com_fabrik/views/element/tmpl/bootstrap.php
administrator/components/com_fabrik/views/element/tmpl/edit.php
administrator/components/com_fabrik/views/elements/tmpl/copyselectgroup.php

**Comment by skurvish** [comment]
Those were the only files that linked the mootools library so those are the only places I updated.

**Comment by joomlahenk** [comment]
OK, I will find out myself and update if needed

**Pull request merged**
