### PR TITLE
Correct form buttons for BS5.

### PR DESCRIPTION
**Pull request by skurvish**
Change the various markup for BS5 for forms and lists.

### CODE REVIEW

**Comment by joomlahenk** [comment]
Yes, there is a lot more BS5 to do. It's all in various files (.php .js) sometimes hard to find. I am doing the ones for the list filters and modals.
Possible we get an issue later with removing classes like class="fabrikCustomButtons. It may be used in some CSS or used in an  application. So maybe just leave those?

**Comment by skurvish** [comment]
I suggest leaving them for now. Later, as we get closer, rename the actual css definition to something else and then we can review the layouts and see if anything broke. If it only broke a little we can fix them one-by-one, otherwise we take away the rename and leave it as is.

**Comment by trob** [comment]
I would leave as much as (and change as little as) possible as long as it doesn't hurt anything.

**Comment by joomlahenk** [comment]
Agreed "Just make it work"

**Pull request merged**
