### PR TITLE
Hopefully now fixed the jdate default issue

### PR DESCRIPTION
**Pull request by skurvish**
Issue #377

### CODE REVIEW

**Comment by joomlahenk** [comment]
Deprecated: DateTime::__construct() is solved now but instead we have a different one:
Deprecated: urldecode(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/j4test/plugins/fabrik_element/jdate/jdate.php on line 596

**Comment by skurvish** [comment]
Where are you seeing this? i.e. what are you doing at the time?

**Comment by joomlahenk** [comment]
I don't know what fixes the change in administrator/components/com_fabrik/models/elements.php

**Comment by skurvish** [comment]
Just a couple of deprecated errors I saw in the list view.

**Comment by joomlahenk** [comment]
I see Deprecated: urldecode(): the same way as I saw Deprecated: DateTime:
Just add a new record like I did before. It's only on add, not on edit.

**Comment by skurvish** [comment]
try PR #404

**Comment by joomlahenk** [comment]
Tried that => still the same deprecation

**Comment by skurvish** [comment]
Yes, UI was just jumping into the shower when it occurred to me I had made a mistake on that. Try the recent change.

**Comment by joomlahenk** [comment]
I forgot to disable cache. Now Deprecated: urldecode() on line 596 ok, but there is another on line 509.
We may be getting a lot of those php8.1 deprecations.

**Comment by skurvish** [comment]
Fixed in pr #402

**Comment by skurvish** [comment]
Sorry, meant pr #404

**Pull request merged**
