### PR TITLE
Update Install

### PR DESCRIPTION
**Pull request by skurvish**
The update directory is required by the grunt build process so I had to restore it from the master branch.

For some reason the libraries/fabrik directory was being deleted by the fabrik.manifest.class.php file and it should not be. I removed this deletion.

Build of current state works and it installs. It inserts the 2 admin template overrides successfully.

### CODE REVIEW

**Comment by joomlahenk** [comment]
Yes, the libraries/fabrik directory is deleted preflight on purpose and must be in!
In case of upgrade the old libraries/fabrik directory is not removed, causing old no longer used files to stay.
I tested this and was working perfect. Why do you it out? Do you get an issue with it?

**Comment by skurvish** [comment]
When I leave it in the newly installed libraries get wiped and we end up with no libraries. If memory serves the J! installed deleted the install directories before it installs each part of the package so I don't think we need to do it in the pre-flight.

**Comment by joomlahenk** [comment]
I have a different experience and tested it several times: The Fabrik libraries will be overwritten, so old files will remain. I check that and if I don't delete the old stuf it's still there. This is because the old 3.10 libraries were never installed, but copied. That is why I deleted the Fabrik libraries first before they are installed. The new libraries will be installed after preflight, so the new Fabrik libraries will be there when preflight has finished. We don't end up with no libraries.
The Fabrik libraries should not be needed during preflight. They will also not be there during a new install.
So please leave it in.
This is for all code in the install script: it's there on purpose. It took me several hours and 35 reinstalls to test and update. So please leave it all in unless you have a serious issue with it.

**Comment by skurvish** [comment]
Alright, I will do some further testing. The problem I had was if I left that code in there once the install was complete there was no library at all and the Fabrik system plugin threw an exception because the autoloader file was missing. Perhaps instead of deleting the whole directory we can cherry pick?

**Comment by joomlahenk** [comment]
Ah, good you discovered that. This is not what I expected J! would do, because they say preflight is running before any install. That seems to be not completely true.
And yes I tested this, but the library was added later so I didn't discover.

**Pull request merged**
