### PR TITLE
Elementsizes

### PR DESCRIPTION
**Pull request by skurvish**
Updated the sizes throughout. Note: We still require the old ones as anyone who attempts to edit an existing element may have the old ones in the database and if so then the value would not be found in the select list.

An alternative I suppose might be to modify the size when it is read from the database and replace it with the corresponding col-md value when it is displayed. Then if the element is saved the updated value would be stored. If we think this would be better I can look at what would be required.

### CODE REVIEW

**Comment by joomlahenk** [comment]
A lot of these updates will be ok but:
I will check the col-md-* in list.php on my site first.
All inputbox must be form-select or form-control and then we may add col-md-*, but not all require a col-md-*

I didn't checked in, but I already changed admin-filters.js on my site and used form-select-sm and also changed the buttons
For the admin-filters I also needed to change models/list.php and add an item to the CSS file.
The old BS settings are scattered around in several files

I can merge my BS5 setting for the pre-filter first, so you can see how that looks like.
I tried to do the same for the joins, but that does not work. The listform.js is more complicated.
Setting col-md-* for pre-filter and joins is of no use, because the columns are part of a table.

- In J!3 input-xxx are in px, col-md-*. in J!4 are in %.
- col-md-12 does not need to be used as this is the maximum width (100%)

**Comment by joomlahenk** [comment]
Just tested the col-md-* in list.xml:
col-md-* does nothing, because all fields are form-control and form-select
You can try (in chrome) inspect elements and add/remove col-md-* to a form-control or form-select

**Comment by joomlahenk** [comment]
In order to use col-md-* for a form-select and form-control (maybe more) they must be in a div, the div can have col-md-*.
See https://getbootstrap.com/docs/5.0/forms/layout/

**Comment by joomlahenk** [comment]
OK, revert what I said before. I did some more experiments. In order the col-md-* in list.xml to work you must remove the class "controls" in admin/views/list/tmpl/admin_bootstrap_control_group.php

**Comment by joomlahenk** [comment]
This means that all class="controls" must be removed as it overrides col-md-*. This maybe the case for more fabrik classes

**Comment by joomlahenk** [comment]
For now I wouldn't merge this, because most will not work. I will make the changes on my site, test it and then merge.

**Comment by skurvish** [comment]
@joomlahenk Why did you delete the form.xml file?

**Comment by skurvish** [comment]
@joomlahenk I am not able to resolve these conflicts on git, I think you are going to have to do them.

**Comment by joomlahenk** [comment]
I merged all, only not with this PR. You will see it if you do a pull. I deleted form.xml by accident, sorry.
I needed to remove class="controls" in all *_control_group.php files to make the col-md-* work. (controls is a BS2.3.2 class)
So now we have all the col-md-* working in the forms. The result however is disappointing, but the same as in J!3. Some need to be changed.
I couldn't get the col-md-* working for the menu->list->fabrik-options, but it's ok for me now.

I am not able to test all the other updates, we will see what happens. This PR can be closed.

**Comment by joomlahenk** [comment]
I had a merging issue. Hopefully all is repair now?

**Comment by skurvish** [comment]
There are still a number of conflicts below that need correcting.

**Comment by joomlahenk** [comment]
After this PR, I merged administrator/components/com_fabrik/models/forms/form.xml back in.
In components/com_fabrik/layouts/pagination/fabrik-pagination-limitbox.php you added col-md-2 but not form-select, is that on purpose or should it be in?
All others are merged after this PR and I think they should remain this way. You can see the result in lists->new/edit->data->pre-filter->add and in lists->new/edit->data->joins->add

**Comment by skurvish** [comment]
I see you added the form-select, seems to work OK. I am going to close this PR and if I find something else I will open a new one.

**Pull request closed without merging**
