### PR TITLE
First cut at fixing the filter options

### PR DESCRIPTION
**Pull request by skurvish**
Seems to be working. For some reason all the fabrik admin panels are showing the sidebar, haven't figured out why yet.

### CODE REVIEW

**Comment by joomlahenk** [comment]
OK, good job. I will test it.
Do you mean that extra empty sidebar.
I have/had that issue for some time already. At first it only appeared if J! debugging was enabled, but now it's persistant.
My guess is that it is in some .js, because the debugger adds jquery. 
If you look in the page source (inspect) you can see that css is overwritten.

**Comment by joomlahenk** [comment]
in administrator/components/com_fabrik/forms/filter_groups.xml you added
<form addfieldprefix="RegularLabs\Library\Form\Field">
Is this for test only? Most people don't have this I think.

I saw one JHTM again in administrator/components/com_fabrik/views/groups/view.html.php:57

**Comment by skurvish** [comment]
That folder and xml files should be in all installations, it is part of the repo.

I suspect I fixed that JHTML in the other PR. I will confirm tomorrow.

**Comment by trob** [comment]
I merged your -filter branch locally, it's looking good so far.

One issue in elements list: selecting a form won't reduce the groups to this form's groups, it's still showing all groups.

**Comment by skurvish** [comment]
Interesting, I did test that, will have a look.

**Comment by skurvish** [comment]
It is working for me. Clear your Joomla cache?

**Comment by trob** [comment]
Cleared Joomla and browser cache.
But I only merged your skurvish-filter branch (the one from this PR), maybe it's not the one you are on? (-factory seems to be newer)

**Comment by skurvish** [comment]
That is the correct branch and it works for me on that branch. Factory branch incorporates a bunch of classname changes but should not affect the filter branch.

**Comment by joomlahenk** [comment]
Again more conflicts to resolve:

administrator/components/com_fabrik/models/fields/formlist.php
administrator/components/com_fabrik/models/fields/grouplist.php
administrator/components/com_fabrik/models/fields/pluginlist.php
administrator/components/com_fabrik/views/elements/view.html.php
administrator/components/com_fabrik/views/groups/tmpl/bootstrap.php
administrator/components/com_fabrik/views/groups/view.html.php

Is there a way we can prevent this?

**Comment by skurvish** [comment]
Do you want me to resolve these or will you?

i think these types of conflicts will start to be less as we get past the first major hurdles. Afterward we will be working on more focused issues and we won't be as likely to step on each others work.

**Comment by joomlahenk** [comment]
Indeed, but for now it takes time. For plugins this could be easier as their code in not part of the component (mostly).
Also the installer, vendor library and languages, can be updated seperately

**Comment by joomlahenk** [comment]
I will resolve them.

**Pull request merged**
