### PR TITLE
do list menu default.xml like form menu

### PR DESCRIPTION
**Pull request by trob**
List menu default.xml is adding again the listid if the setup is analogue to the form menu.
But I did only a copy/paste, not digging deeper.
Please review

### CODE REVIEW

**Comment by skurvish** [comment]
I think the addfieldpath needs to go on the fieldset. The listid is part of the request fieldset which gets it placed on the main menu configuration and included on the url. I will take a look and see if I can figure out why it is not being populated.

**Comment by skurvish** [comment]
The listID is showing for me on the menu when I look at it in the menu manager.

**Comment by skurvish** [comment]
And it is showing on the link on the menu on the front end.

**Comment by trob** [comment]
Are these old or new list menues?
It was working until this commit and "old" menue items are still doing.
Did you try to add a new one or edit an old one?

I assume it's not the addfilepath but the additional <fields tag + name="request"

As I said: I just did copy/paste form the working form default.xml and now it's working for list, too.
Visualization's defaul.xml has the same structure and is working also.

**Comment by skurvish** [comment]
I added a new one and I do see that the listID is missing, but the menu link opens the correct list. SEF links fail though.

**Pull request merged**
