### PR TITLE
Update layouts as per the BS3 overrides. Some may need additional wor…

### PR DESCRIPTION
**Pull request by skurvish**
…k for BS5, but nothing jumped out at me.

### CODE REVIEW

**Comment by trob** [comment]
Hmm, the BS3 Layouts are already merged and several BS5 adaptions mafe, e.g. list pagination, groub by etc. 
This would override it

**Comment by joomlahenk** [comment]
Great job!
I think in J!4 we have to use the -bs- in data-bs-toggle. 
Till now I didn't see issues with this, but I surely didn't check all the fields and form in the backend and frontend. I  didn't check cascadingdropdown and pagination. How can we test all of this?

**Comment by skurvish** [comment]
I only changed the layouts that needed changing. Those that you had already changed I left alone.

It is true, there may need to be additional mods for BS5 as I pointed out in the initial PR.

**Comment by joomlahenk** [comment]
Please add -bs- in data-toggle, data-trigger, data-placement, data-content, as this is required for BS5

**Comment by skurvish** [comment]
Will do. Just working on the grunt package build. Will do this right afterward.

**Comment by joomlahenk** [comment]
And FText => Text in fabrik-element-date-list-filter-range.php

**Comment by skurvish** [comment]
Ready to merge. Fixed the FText as well in a number of spots.

**Pull request merged**
