### PR TITLE
Revert "Update element.php, once again JForm grept in"

### PR DESCRIPTION
**Pull request by trob**
Reverts joomlahenk/fabrik#59

### CODE REVIEW

**Comment by trob** [comment]
plugin.php is already fixed by @joomlahenk in https://github.com/joomlahenk/fabrik/commit/e91dde003aac41d5bef780f64a48050aa39dabb9

**Comment by trob** [comment]
why did you close this without merging?

**Comment by joomlahenk** [comment]
Because I merged it already.

**Comment by trob** [comment]
It doesn't seem so, the code in henk40 branch is still the unreverted
image

instead of $plugin_form = $plugin->getJForm();

**Comment by joomlahenk** [comment]
This is in components/com_fabrik/models/plugin.php as far as I knew and after I did a pull it is changed on my side.
I see it also in administrator/components/com_fabrik/models/plugin.php, I will change it there also and search for more and merge if done.

**Comment by joomlahenk** [comment]
OK, I only changed conponents/com_fabrik/models/plugin.php and missed the one in admin/components/com_fabrik/models/element.php. Should be ok now, if not let me know

**Pull request closed without merging**
