### PR TITLE
Add some missing Factory use statements

### PR DESCRIPTION
**Pull request by skurvish**
4 files misssed.

### CODE REVIEW

**Comment by joomlahenk** [comment]
There are more missing J's

**Comment by skurvish** [comment]
I need to know the classnames that are missing them.

**Comment by joomlahenk** [comment]
Also, you didn't change classnames in all files in admin/models/fields. Only "extend" classnames should change.

**Comment by skurvish** [comment]
Can you give me an example?

**Comment by joomlahenk** [comment]
Example: admin/models/fields/ascendingdescending.php JHTML And most every other file in that folder.
However you do not need to change as most of the old classes still work (see the joomla classmap). It will be required for J!5.
Only if you change some, you should change all.
I must admit this is very tricky: for the fabrik fields they created new classes with J... while that should be something like Fab (or just F). Also it possible that some "Fab" classes are inherited somewhere, which makes it more complicated.

**Comment by skurvish** [comment]
Fixed all the JHTML's.

**Comment by joomlahenk** [comment]
About:
HTMLHelperstylesheet
HTMLHelperimage
HTMLHelpercalendar
HTMLHelperdate

I think you need add an :: after HTMLHelper. Since these are functions of HTMLHelper and do not exist as a class (see classmap).
I see you just do a search and replace, I wish it was that simple. I would advise against that, it can cause issues.

**Comment by skurvish** [comment]
Yes, I am looking at that now.

**Comment by skurvish** [comment]
Hold off on merging this obviously. I am worn out today but will get back at it tomorrow morning. The filter stuff took me quite a while to get a handle on how to get it to work.

**Comment by joomlahenk** [comment]
Sure, you did a lot of work. We also have less code now.

**Comment by skurvish** [comment]
Let me know if you find anything else. It is cocktail hour now for me.

**Comment by joomlahenk** [comment]
You didn't update the classnames of several fabrik fields:

admin/models/fields/collation.php
admin/models/fields/fabrikmodalrepeat.php
admin/models/fields/helplink.php
admin/models/fields/hiddenparams.php
admin/models/fields/mailgunwebhook.php
admin/models/fields/stripewebhook.php
admin/models/fields/suboptions.php
admin/models/fields/uploadsize.php

I just merged those so please do a pull first and then make your changes.

**Comment by joomlahenk** [comment]
If you are sure you did all FText to Text, you can also remove /libraries/fabrik/fabrik/Helpers/Text.php and remove the alias in components/com_fabrik/helpers/legacy/aliasses.php

**Comment by skurvish** [comment]
Updated as above. Regarding those fabrik fields, I do not see any issue in them right now so I assume you made the appropriate changes and merged. If not let me know what you see as still wrong.

**Comment by joomlahenk** [comment]
I just did a merge for the visualization files and did not realize you were also updating them, resulting in a merge conflict.
I think we need to agree which files, who is working on so others don't tough them before they are merged.
Or put a lock on files ? Don't know if that's possible. 
Now I spend most time getting GitHub up to date and resolving conflicts

**Pull request merged**
