### PR TITLE
Pagination

### PR DESCRIPTION
**Pull request by skurvish**
Fixed.

### CODE REVIEW

**Comment by joomlahenk** [comment]
size=".." is of no use. It does not set any size. size can be used in BS5 for multiselect. Please remove if encountered.
Is pagination checked and working as expected?

**Comment by skurvish** [comment]
Henk, where exactly are you talking about? I see no size=".." in this??

**Comment by joomlahenk** [comment]
components/com_fabrik/layouts/pagination/fabrik-pagination-limitbox.php
$attributes = 'class="inputbox form-select" size="1" onchange="' . $js . '"';

They do no harm, just do nothing. But can cause confusing/issue if used for multiselect

**Comment by skurvish** [comment]
That was already in place before I made any changes. As you say it does not harm that we can see. If at some point we see it causing issues we can remove it. One never knows what magic is going on in javascript somewhere that relies on this tsuff.

**Comment by joomlahenk** [comment]
I am unable to test this. So I assume it works.

**Pull request merged**
