### PR TITLE
goomapviz

### PR DESCRIPTION
**Pull request by trob**
mootools-core and mootools-more: all Array.from changed to Array.mofrom because Google doe not longer accept the "override", see also https://fabrikar.com/forums/index.php?threads/google-maps-element.52933/page-2#post-278994

### CODE REVIEW

**Comment by joomlahenk** [comment]
Is Lizt still used? I couldn't find where it was used and removed it. Same for fabble.

**Comment by joomlahenk** [comment]
OK, I see googlemaps is the only one to use it. For now I aggree to put back Lizt, but some time later we better put this in the googlemap plugin. This can be very simple: just add getElements function in FabrikModelGooglemap

**Comment by joomlahenk** [comment]
May even be more simple. Can you test that?

**Comment by trob** [comment]
`Can you test that?` Test what?

**Pull request merged**
